version: '{branch}-{build}'

os: Visual Studio 2015

init:
  # Create our AppVeyor version
  - ps: $env:commit = $env:appveyor_repo_commit.SubString(0,7)
  - ps: Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch,$env:appveyor_build_number,$env:commit )

environment:
  matrix:
    - arch: x86
      compiler: mingw

platform:
  - x64

configuration:  
  - release

cache:
  - C:\Qt\4.8.7 -> .appveyor.yml
 
install:
  # dependencies
  - choco install curl 7zip 
  - mkdir extern
  - cd extern

  ## setup environment
  # Toolchain - MinGW
  - curl https://www.dropbox.com/s/2r03pyyuhuwn37m/MinGW.zip?dl=1 -O -J -L
  - 7z x MinGW.zip > nul
  - set "MINGWDIR=%cd%\MinGW"
  - set "PATH=%MINGWDIR%\bin;%PATH%"
  - set make="mingw32-make.exe"

  # OPEN SSL
  - curl https://www.dropbox.com/s/cvczidpjg39nz3v/OpenSSL101c.zip?dl=1 -O -J -L
  - 7z x OpenSSL101c.zip > nul
  - move OpenSSL C:\
  - set "OPENSSLDIR=C:\OpenSSL"

  # QT  
  - curl https://www.dropbox.com/s/rennfrbuq2rdpjh/qt487-mingw32.zip?dl=1 -O -J -L
  - 7z x qt487-mingw32.zip > nul
  - set "QTDIR=%cd%\Qt\4.8.7"
  - dir %QTDIR%
  - set "PATH=%QTDIR%\bin;%PATH%"
  
before_build:
  # Prepare the out-of-source build directory.
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake -spec win32-g++-4.6 -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%
  
build_script:
  # Compile it and check for .exe
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - '%make%'
  - dir /b /s *.exe

after_build:
  - set BIN=MambaWebBrowser
  - dir /b /s *.exe
  - mkdir deploy
  - copy %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\%BIN%.exe deploy\%BIN%.exe
  - copy %OPENSSLDIR%\bin\libeay32.dll deploy\
  - copy %OPENSSLDIR%\bin\ssleay32.dll deploy\
  - copy %MINGWDIR%\bin\libgcc_s_dw2-1.dll deploy\
  - copy "%MINGWDIR%\bin\libstdc++-6.dll" deploy\
  - copy "%MINGWDIR%\bin\libwinpthread-1.dll" deploy\
  - copy %QTDIR%\bin\QtCore4.dll deploy\
  - copy %QTDIR%\bin\QtGui4.dll deploy\
  - copy %QTDIR%\bin\QtNetwork4.dll deploy\
  - copy %QTDIR%\bin\QtWebKit4.dll deploy\
  - 7z a -tzip %BIN%_%CONFIGURATION%.zip .\deploy\* -r
  - copy %APPVEYOR_BUILD_FOLDER%-build\%BIN%_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\%BIN%_%CONFIGURATION%.zip
  - dir /b /s *.zip

artifacts:
  - path: '%BIN%_%CONFIGURATION%.zip'
    name: '%BIN%'

deploy:
  - provider: GitHub
    release: continuous
    artifact: '%BIN%'
    draft: false
    prerelease: true
    auth_token:
      secure: p0RIEM3bMprm7t6GO2CdzBNAbItuPEYKWbvMFiHss/pP7MvlifDyVP2UMcIPrpc+